sudo: required
language: generic
services: docker
env:
- HHVM_VERSION=latest
- HHVM_VERSION=nightly
install:
- docker pull hhvm/hhvm:$HHVM_VERSION
script:
- docker run --rm -w /var/source -v $(pwd):/var/source hhvm/hhvm:$HHVM_VERSION ./.travis.sh
notifications:
  slack:
    secure: GjYt2/ypF4iqxNB4OUTew+pBCEHzoZNp6uW6nVi5+fLXBy0CXGSYOAoiL+6UKY/Ze1e8KYeECx6kNZhx2wDPJq/yEfQsH/R500OhLHwlxIyeVqeOTjUVjlgWgeq4miG+q7tDj3E2se4CSNR68KwIt/P/fdsrBhR16JheCfIDK14EvNz2tBJ823p5461SWkWwn0ZoIIXzR67JSfo+f1bmD44Zeq1BV+e5ik/rrp/zg5awXciUjNh5BodVwebS5v1kXF5hZhKLqYmsU/Ryzd9ZrbNyh5EIQxuPV4fK2nz2u3AihjsyyBctnbZziYC4TwoppNeNVrEmquVY29mi5WqYh0eC+RbU4+UZeXeSi8tzB+FI3xu7rWObR+J8Lmy9kwLcqrU0/ncfuFs9ytVQ2DKkuNUCqlKxr/GmY/kU2oNjzAfHvID3DB3kGNidlTHRf9e+WNLqobkGfdFWt8YwUSDrzYmNnii0LVFDPlnUpIpEYGO0sCIopKtrN6qR4g0Hx+jqpwagpe2K+9jCsY8jt7blCaye4b7m6WzUJdQPMaJLTdC160tQlFJ72HuyJD9b+myx7Ym113EAyTbGY5sRnj3WJCslijoJRFwcL5sXNZD88ELoMPZiE6uylz0jgjZbSIJtAImXLxVIgKgU5+UK8txo5L4X8XjUHumPumSNBIMkMmQ=
